// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smhgnynmfipqbkmbpgvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtaGdueW5tZmlwcWJrbWJwZ3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NDAwNDcsImV4cCI6MjA2MjQxNjA0N30.HPVs9HyO5UAiAEAS5Zy5ZynGQAQPcZnN_bzTXCVIdTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);